"""Added travel_multiplier to Region

Revision ID: 15cb2e66f74
Revises: 4effbf7f3fe7
Create Date: 2015-03-14 10:19:58.780850

"""

# revision identifiers, used by Alembic.
revision = '15cb2e66f74'
down_revision = '4effbf7f3fe7'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    eval("upgrade_%s" % engine_name)()


def downgrade(engine_name):
    eval("downgrade_%s" % engine_name)()





def upgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('travel_multiplier', sa.Float(), server_default='1.0', nullable=False))
    ### end Alembic commands ###


def downgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'travel_multiplier')
    ### end Alembic commands ###


def upgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('travel_multiplier', sa.Float(), server_default='1.0', nullable=False))
    ### end Alembic commands ###


def downgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'travel_multiplier')
    ### end Alembic commands ###


def upgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('travel_multiplier', sa.Float(), server_default='1.0', nullable=False))
    ### end Alembic commands ###


def downgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'travel_multiplier')
    ### end Alembic commands ###

