"""sectors part 2

Revision ID: 2a147893565a
Revises: 38a9acba95bd
Create Date: 2015-03-28 13:23:09.248011

"""

# revision identifiers, used by Alembic.
revision = '2a147893565a'
down_revision = '38a9acba95bd'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    eval("upgrade_%s" % engine_name)()


def downgrade(engine_name):
    eval("downgrade_%s" % engine_name)()





def upgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marching_orders', sa.Column('dest_sector', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marching_orders', 'dest_sector')
    ### end Alembic commands ###


def upgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marching_orders', sa.Column('dest_sector', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marching_orders', 'dest_sector')
    ### end Alembic commands ###


def upgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marching_orders', sa.Column('dest_sector', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marching_orders', 'dest_sector')
    ### end Alembic commands ###

