"""Added Buffs

Revision ID: 2de0d2488523
Revises: 5274feda1fa6
Create Date: 2013-08-06 20:25:42.194935

"""

# revision identifiers, used by Alembic.
revision = '2de0d2488523'
down_revision = '5274feda1fa6'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    eval("upgrade_%s" % engine_name)()


def downgrade(engine_name):
    eval("downgrade_%s" % engine_name)()





def upgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('internal', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('expires', sa.Integer(), nullable=True),
    sa.Column('skirmish_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['skirmish_id'], ['skirmish_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buffs')
    ### end Alembic commands ###


def upgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('internal', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('expires', sa.Integer(), nullable=True),
    sa.Column('skirmish_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['skirmish_id'], ['skirmish_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buffs')
    ### end Alembic commands ###


def upgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('internal', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('expires', sa.Integer(), nullable=True),
    sa.Column('skirmish_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['skirmish_id'], ['skirmish_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buffs')
    ### end Alembic commands ###

