"""Added recruit time to user table

Revision ID: 2e37930ecb54
Revises: 2de0d2488523
Create Date: 2013-08-15 18:35:30.985537

"""

# revision identifiers, used by Alembic.
revision = '2e37930ecb54'
down_revision = '2de0d2488523'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    eval("upgrade_%s" % engine_name)()


def downgrade(engine_name):
    eval("downgrade_%s" % engine_name)()





def upgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recruited', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recruited')
    ### end Alembic commands ###


def upgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recruited', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recruited')
    ### end Alembic commands ###


def upgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recruited', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recruited')
    ### end Alembic commands ###

