"""sectors

Revision ID: 38a9acba95bd
Revises: 15cb2e66f74
Create Date: 2015-03-28 13:06:40.812704

"""

# revision identifiers, used by Alembic.
revision = '38a9acba95bd'
down_revision = '15cb2e66f74'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    eval("upgrade_%s" % engine_name)()


def downgrade(engine_name):
    eval("downgrade_%s" % engine_name)()





def upgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skirmish_actions', sa.Column('sector', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sector', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sector')
    op.drop_column('skirmish_actions', 'sector')
    ### end Alembic commands ###


def upgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skirmish_actions', sa.Column('sector', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sector', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sector')
    op.drop_column('skirmish_actions', 'sector')
    ### end Alembic commands ###


def upgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skirmish_actions', sa.Column('sector', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sector', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sector')
    op.drop_column('skirmish_actions', 'sector')
    ### end Alembic commands ###

