"""Initial

Revision ID: 391058ac6f40
Revises: None
Create Date: 2013-07-05 18:13:19.338367

"""

# revision identifiers, used by Alembic.
revision = '391058ac6f40'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    eval("upgrade_%s" % engine_name)()


def downgrade(engine_name):
    eval("downgrade_%s" % engine_name)()





def upgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('srname', sa.String(length=255), nullable=True),
    sa.Column('capital', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('eternal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begins', sa.Integer(), nullable=True),
    sa.Column('ends', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.String(), nullable=True),
    sa.Column('victor', sa.Integer(), nullable=True),
    sa.Column('score0', sa.Integer(), nullable=True),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('lockout', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('loyalists', sa.Integer(), nullable=True),
    sa.Column('committed_loyalists', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=True),
    sa.Column('defectable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region_to_region',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('marching_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arrival', sa.Integer(), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('dest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dest_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skirmish_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('hinder', sa.Boolean(), nullable=True),
    sa.Column('troop_type', sa.String(), nullable=True),
    sa.Column('victor', sa.Integer(), nullable=True),
    sa.Column('vp', sa.Integer(), nullable=True),
    sa.Column('margin', sa.Integer(), nullable=True),
    sa.Column('unopposed', sa.Boolean(), nullable=True),
    sa.Column('battle_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['skirmish_actions.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id36', sa.String(), nullable=True),
    sa.Column('battle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed')
    op.drop_table('skirmish_actions')
    op.drop_table('marching_orders')
    op.drop_table('region_to_region')
    op.drop_table('users')
    op.drop_table('battles')
    op.drop_table('regions')
    ### end Alembic commands ###


def upgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('srname', sa.String(length=255), nullable=True),
    sa.Column('capital', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('eternal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begins', sa.Integer(), nullable=True),
    sa.Column('ends', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.String(), nullable=True),
    sa.Column('victor', sa.Integer(), nullable=True),
    sa.Column('score0', sa.Integer(), nullable=True),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('lockout', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('loyalists', sa.Integer(), nullable=True),
    sa.Column('committed_loyalists', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=True),
    sa.Column('defectable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region_to_region',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('marching_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arrival', sa.Integer(), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('dest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dest_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skirmish_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('hinder', sa.Boolean(), nullable=True),
    sa.Column('troop_type', sa.String(), nullable=True),
    sa.Column('victor', sa.Integer(), nullable=True),
    sa.Column('vp', sa.Integer(), nullable=True),
    sa.Column('margin', sa.Integer(), nullable=True),
    sa.Column('unopposed', sa.Boolean(), nullable=True),
    sa.Column('battle_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['skirmish_actions.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id36', sa.String(), nullable=True),
    sa.Column('battle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed')
    op.drop_table('skirmish_actions')
    op.drop_table('marching_orders')
    op.drop_table('region_to_region')
    op.drop_table('users')
    op.drop_table('battles')
    op.drop_table('regions')
    ### end Alembic commands ###


def upgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('srname', sa.String(length=255), nullable=True),
    sa.Column('capital', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('eternal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begins', sa.Integer(), nullable=True),
    sa.Column('ends', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.String(), nullable=True),
    sa.Column('victor', sa.Integer(), nullable=True),
    sa.Column('score0', sa.Integer(), nullable=True),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('lockout', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('loyalists', sa.Integer(), nullable=True),
    sa.Column('committed_loyalists', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('leader', sa.Integer(), nullable=True),
    sa.Column('defectable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region_to_region',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('marching_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arrival', sa.Integer(), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('dest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dest_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skirmish_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('hinder', sa.Boolean(), nullable=True),
    sa.Column('troop_type', sa.String(), nullable=True),
    sa.Column('victor', sa.Integer(), nullable=True),
    sa.Column('vp', sa.Integer(), nullable=True),
    sa.Column('margin', sa.Integer(), nullable=True),
    sa.Column('unopposed', sa.Boolean(), nullable=True),
    sa.Column('battle_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['skirmish_actions.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id36', sa.String(), nullable=True),
    sa.Column('battle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed')
    op.drop_table('skirmish_actions')
    op.drop_table('marching_orders')
    op.drop_table('region_to_region')
    op.drop_table('users')
    op.drop_table('battles')
    op.drop_table('regions')
    ### end Alembic commands ###

