"""Added display_ends to skirmishes

Revision ID: 42918bb1dffe
Revises: 4638ed8c54d9
Create Date: 2013-12-05 16:35:02.513937

"""

# revision identifiers, used by Alembic.
revision = '42918bb1dffe'
down_revision = '4638ed8c54d9'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    eval("upgrade_%s" % engine_name)()


def downgrade(engine_name):
    eval("downgrade_%s" % engine_name)()





def upgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skirmish_actions', sa.Column('display_ends', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skirmish_actions', 'display_ends')
    ### end Alembic commands ###


def upgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skirmish_actions', sa.Column('display_ends', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skirmish_actions', 'display_ends')
    ### end Alembic commands ###


def upgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skirmish_actions', sa.Column('display_ends', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skirmish_actions', 'display_ends')
    ### end Alembic commands ###

