"""Added ends and resolved columns to SkirmishAction

Revision ID: 4638ed8c54d9
Revises: 41fe909190d3
Create Date: 2013-11-12 00:33:13.881217

"""

# revision identifiers, used by Alembic.
revision = '4638ed8c54d9'
down_revision = '41fe909190d3'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    eval("upgrade_%s" % engine_name)()


def downgrade(engine_name):
    eval("downgrade_%s" % engine_name)()





def upgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skirmish_actions', sa.Column('resolved', sa.Boolean(), nullable=True))
    op.add_column('skirmish_actions', sa.Column('ends', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skirmish_actions', 'ends')
    op.drop_column('skirmish_actions', 'resolved')
    ### end Alembic commands ###


def upgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skirmish_actions', sa.Column('resolved', sa.Boolean(), nullable=True))
    op.add_column('skirmish_actions', sa.Column('ends', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skirmish_actions', 'ends')
    op.drop_column('skirmish_actions', 'resolved')
    ### end Alembic commands ###


def upgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skirmish_actions', sa.Column('resolved', sa.Boolean(), nullable=True))
    op.add_column('skirmish_actions', sa.Column('ends', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skirmish_actions', 'ends')
    op.drop_column('skirmish_actions', 'resolved')
    ### end Alembic commands ###

