"""Added aliases

Revision ID: 4effbf7f3fe7
Revises: 42918bb1dffe
Create Date: 2014-12-30 11:21:47.379369

"""

# revision identifiers, used by Alembic.
revision = '4effbf7f3fe7'
down_revision = '42918bb1dffe'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    eval("upgrade_%s" % engine_name)()


def downgrade(engine_name):
    eval("downgrade_%s" % engine_name)()





def upgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_engine1():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aliases')
    ### end Alembic commands ###


def upgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_engine2():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aliases')
    ### end Alembic commands ###


def upgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_engine3():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aliases')
    ### end Alembic commands ###

